install.packages("config")
install.packages("arules")
install.packages("mclust")
install.packages("rpart")
install.packages("parallel")
#install.packages("bnlearn")
install.packages("https://cran.r-project.org/src/contrib/Archive/bnlearn/bnlearn_4.6.1.tar.gz", repos=NULL, type="source")
install.packages("stringr")
install.packages("igraph")
install.packages("randomForest")
install.packages("randomForestSRC")
install.packages("reticulate")
install.packages("Rcpp")
install.packages("Matching")
install.packages("LaplacesDemon")
install.packages("acepack")
install.packages("Hmisc")
install.packages("corrplot")
install.packages("ggpubr")
install.packages("plyr")
install.packages("tidyverse", dependencies = TRUE)