[project]
name = "vambn"
version = "3.0.0"
description = "Variational Autoencoder"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name= "Manuel Lentzen", email= "manuel.lentzen@scai.fraunhofer.de"},
    {name= "Sophia Krix", email= "sophia.krix@scai.fraunhofer.de"},
    {name= "Diego Valderama", email= "diego.felipe.valderrama.nino@scai.fraunhofer.de"},
    {name= "Tamara Raschka", email= "tamara.raschka@scai.fraunhofer.de"},
]
dependencies = [
    "matplotlib>=3.10.8",
    "mkdocs>=1.6.1",
    "mlflow>=3.7.0",
    "optuna[postgresql]>=4.6.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "psycopg2-binary>=2.9.11",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "snakemake>=9.14.4",
    "syndat>=0.13.6",
    "torch>=2.9.1",
    "typeguard>=4.4.4",
    "typer>=0.20.0",
]

