name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install toml
      run: pip install toml
    
    - name: Get Version
      id: get_version
      run: echo "VERSION=$(python .github/scripts/read_version.py)" >> $GITHUB_ENV
    
    - name: Build & Push Docker Image for mlflow
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile.mlflow
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/mlflow:latest
          ghcr.io/${{ github.repository }}/mlflow:${{ env.VERSION }}

    
    - name: Build & Push Docker Image for vambn
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile.vambn
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/vambn:latest
          ghcr.io/${{ github.repository }}/vambn:${{ env.VERSION }}

